### ISSUE TITLE
add semantic-diff cmd

### ISSUE THREAD

**Issue by adisos** [np-guard/netpol-analyzer#154]
allow connectivity-diff between two directories containing workloads and netpols manifests.

**Comment by shireenf-ibm** [comment]
planned PRs (on the semantic_diff_command branch):
[] adding diff command (pr #174)
[] adding diff functionality - diff conns on common peers
[] writing diff output 
[] support multiple formats

**Comment by adisos** [comment]
- diff-part1: handle connection equality issue
- diff-part2: let added tests run with unit-tests, review 
- diff-part3: output formats (txt,csv,md)
- diff-part4: dot format 

consider for later:
- merge disjoint-ip-blocks in output where possible
- mark peers which are removed/added

**Comment by adisos** [comment]
for the case of an added/removed workload, let's add to the diff-type that info.
for example, in the current report if we have `src: A, dst: B, dir1: NoConn, dir2: TCP, diff-type: added` , and if `B` is a new workload that does not exist in dir1, then the report should be with `diff-type: added (workload A added)`
