### ISSUE TITLE
SemanticDiff tests from NCA which are not imported yet

### ISSUE THREAD

**Issue by shireenf-ibm** [np-guard/netpol-analyzer#200]
This issue lists the k8s semanticDiff in NCA which could not be used for netpol-analyzer testing and why not, to consider a future support:

- [x]  [semanticDiff-same-topologies-scheme](https://github.com/IBM/network-config-analyzer/blob/3c485449a02b7f28030a87362e6c78d83a5a1a48/tests/k8s_testcases/example_policies/tests-different-topologies/semanticDiff-same-topologies-scheme.yaml) : 

- [x]  [semanticDiff-different-topologies-scheme.yaml](https://github.com/IBM/network-config-analyzer/blob/ebe0e452759ef3a06cfdcf79cfd4526ae2c413ea/tests/k8s_testcases/example_policies/tests-different-topologies/semanticDiff-different-topologies-scheme.yaml) (queries : semantic_diff_a_to_b, semantic_diff_b_to_a, semantic_diff_disjoint_old1_config_a, semantic_diff_a_to_b_with_ipBlock)

 (**First task below**)
the podList in these tests contains multiple pods with different labels, but same `ownerReferences` name, a case that is not supported in netpol-analyzer 

------------------------------------------------------

- [x]  [namedPorts-scheme.yaml](https://github.com/IBM/network-config-analyzer/blob/3c485449a02b7f28030a87362e6c78d83a5a1a48/tests/k8s_testcases/example_policies/tests-different-topologies/namedPorts-scheme.yaml):

1. First SemanticDiff in the file:  **RESOLVED** :
this test is legal, the netpols select all pods and try to connect only to the pods with specific named-ports. currently, netpol-analyzer, raises an error in case a selected pod does not contain a named port/ that specific named-port (a bug to be resolved in #199)
2. Second SemanticDiff in the file : 
running the `list` command on the relevant dirs, gives different connections for that pod each time >> **same problem as first task below** (see comment below)

-------------------------------------

- [x]  [semanticDiff-multiple-resources-scheme.yaml](https://github.com/IBM/network-config-analyzer/blob/ebe0e452759ef3a06cfdcf79cfd4526ae2c413ea/tests/k8s_testcases/example_policies/tests-different-topologies/semanticDiff-multiple-resources-scheme.yaml):(first query) - **first task below :** policy's rule in this test select the pods with `app: bank-ui-selector`, which is not shared by all pods with same `ownerReferences` name 

- [x]  [semanticDiff-IpBlocks-different-topologies-scheme.yaml](https://github.com/IBM/network-config-analyzer/blob/ebe0e452759ef3a06cfdcf79cfd4526ae2c413ea/tests/k8s_testcases/example_policies/tests-different-topologies/semanticDiff-IpBlocks-different-topologies-scheme.yaml) - **first task below :** all policies in this test select the pods with `tier=frontend`, which is not shared by all pods with same `ownerReferences` name - (see comment below for example (same podslist in both tests))

  **still not added** getting different diff results for each run

**Comment by shireenf-ibm** [comment]
- [ ] add warn message to inform that the case of multiple pods with different labels but same ownerReferences name is not supported

**Comment by shireenf-ibm** [comment]
> * [namedPorts-scheme.yaml](https://github.com/IBM/network-config-analyzer/blob/3c485449a02b7f28030a87362e6c78d83a5a1a48/tests/k8s_testcases/example_policies/tests-different-topologies/namedPorts-scheme.yaml):
>  Second SemanticDiff in the file : TODO, understand and fix : weird behavior of the kube-system/tiller-deploy-5c45c9966b[ReplicaSet]
running the list command on the relevant dirs, gives different connections for that pod each time

 from analyzing the results and debugging the test in this file , it fails because of the case of existing pods with same `ownerReferences name` but different labels for each. 
 In this test, the Ingress rule in the policy requires following:
 

```
 - from:
      - podSelector:
          matchLabels:
            tier: frontend
```
however, in the pods list we have for example these pods which have same `ownerReferences name` with the matching label for one and without for the second (the reason of the different results each time)
-> with label:
```
"metadata": {
          "name": "kube-fluentd-h6rjg",
          "namespace": "kube-system",
          "labels": {
            "app": "kube-fluentd",
            "tier": "frontend",
            "controller-revision-hash": "2787683658",
            "pod-template-generation": "20"
          },
          "ownerReferences": [
            {
              "apiVersion": "extensions/v1beta1",
              "kind": "DaemonSet",
              "name": "kube-fluentd",
```
-> without label:
```
"metadata": {
          "name": "kube-fluentd-qmp4w",
          "namespace": "kube-system",
          "labels": {
            "controller-revision-hash": "2787683658",
            "pod-template-generation": "20",
            "app": "kube-fluentd"
          },
          "ownerReferences": [
            {
              "apiVersion": "extensions/v1beta1",
              "kind": "DaemonSet",
              "name": "kube-fluentd",
```

**so No Bug, but we should think how to continue after the warn message, as almost all NCA based tests has the same podlist of this** (in cases like this where the policy rules select pods by labels, we can not continue, as the results will not be unique for different runs, but when there is no specified "selecting rules", it will pass always

**Comment by adisos** [comment]
The non-deterministic output was because the output is in level of workloads, but the input resources were pods , such that it depended on the order of traversal and generation of workloads from pods? (in two runs might have creates same workload with different labels, depending on which pod has been handled first?)

**Comment by shireenf-ibm** [comment]
> The non-deterministic output was because the output is in level of workloads, but the input resources were pods , such that it depended on the order of traversal and generation of workloads from pods? (in two runs might have creates same workload with different labels, depending on which pod has been handled first?)

yes, two runs may have different results, since the workload (with ownerRef. name) gets the labels of the first pod it was created from

**Comment by adisos** [comment]
The check for consistent labels per pods  of same owner is done at `GetPeersList()`, where the conversions to peers in level of workloads takes place.
