### ISSUE TITLE
avoid duplicated const in several packages

### ISSUE THREAD

**Issue by shireenf-ibm** [np-guard/netpol-analyzer#203]
currently we have same `const IngressPodName = "ingress-controller"`
in both `ingress-analyzer` (internal to `Connlist`) and `diff` packages 
- to avoid this duplication by exporting  (TBD: where to export it)

**Comment by adisos** [comment]
additional duplication to consider: interfaces `ConnListError` and `DiffEror` are the same

**Comment by shireenf-ibm** [comment]
- [ ] resolve `const IngressPodName = "ingress-controller"` duplication
- [ ]  avoid hard-coded/duplicated error messages for testing. Ideally, we should have a pkg with defined error strings as const values , that will be used both for error generation and for testing errors strings cross-packages. (see [example](https://github.com/np-guard/netpol-analyzer/pull/244#discussion_r1345735863))
